name: Check using biome with bun
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
jobs:
  test:
    strategy:
      matrix:
        bun_version: [1.0.25]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Bun ${{ matrix.bun_version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun_version }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: bun run lint:commit -- --from HEAD~1 --to HEAD --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: bun run lint:commit -- --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Check using biome ci
        run: bun run ci
