name: Release
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  release:
    strategy:
      matrix:
        bun_version: [1.0.25]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Bun ${{ matrix.bun_version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun_version }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Semantic Release
        run: bunx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
